name: tsumeshogi-bot

on:
  workflow_dispatch:

jobs:
  bot:
    runs-on: ubuntu-latest
    env:
      BSKY_IDENTIFIER: ${{ secrets.BSKY_IDENTIFIER }}
      BSKY_PASSWORD: ${{ secrets.BSKY_PASSWORD }}
    steps:
      - uses: actions/checkout@v4
      - name: Run
        run: cargo run
