name: tsumeshogi-bot

on:
  schedule:
    - cron: "0 */3 * * *"
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  bot:
    runs-on: ubuntu-latest
    env:
      BSKY_IDENTIFIER: ${{ secrets.BSKY_IDENTIFIER }}
      BSKY_PASSWORD: ${{ secrets.BSKY_PASSWORD }}
    steps:
      - uses: actions/checkout@v4
      # https://github.com/actions/cache/blob/main/examples.md#rust---cargo
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Run
        run: cargo run
